Output demo.gif

# Set up a 1200x600 terminal with 46px font.
Set WindowBar Colorful
Set FontSize 32
Set Width 1600
Set Height 900
Set Margin 40
Set MarginFill "#FFFFFF"
Set BorderRadius 20
Set Framerate 60
Set Theme "Catppuccin Latte"
Set TypingSpeed 12ms
Set PlaybackSpeed 0.3

Hide
Type "cd .."
Enter
Type "clear"
Enter
Show

Type "npm run test:example"

Sleep 1ms

Enter

# Admire the output for a bit.
Sleep 5s

